<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8afd95bf-6d4c-4846-b81b-6994fbf973cd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.SmartEnum.SystemTextJson" Version="8.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="3.7.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="BackgroundServices\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Portfolio.Application\Portfolio.Application.csproj" />
    <ProjectReference Include="..\Portfolio.Infrastructure\Portfolio.Infrastructure.csproj" />
  </ItemGroup>

</Project>
