// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Infrastructure.Persistence;

#nullable disable

namespace Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioContext))]
    [Migration("20260228213335_AddedEntitiesAssetAndAssetType")]
    partial class AddedEntitiesAssetAndAssetType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssetTypeCode");

                    b.ToTable("Asset", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.AssetType", b =>
                {
                    b.Property<string>("Value")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Value");

                    b.ToTable("AssetType", (string)null);

                    b.HasData(
                        new
                        {
                            Value = "CRYPTO",
                            Name = "Crypto"
                        },
                        new
                        {
                            Value = "FIAT",
                            Name = "Fiat"
                        },
                        new
                        {
                            Value = "STOCK",
                            Name = "Stock"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<decimal>("AmountSpent")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<string>("FeeAsset")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("FeeAssetPriceInEur")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<decimal?>("FeeAssetPriceInUsd")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<string>("FromAssetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("FromAssetPriceInEur")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<decimal>("FromAssetPriceInUsd")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<string>("Notes")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToAssetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionTypeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TransactionType");

                    b.Property<decimal?>("UsdEurExchangeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.HasKey("Id")
                        .HasName("PK__YourTabl__3214EC0704F226F8");

                    b.HasIndex("TransactionTypeCode");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.TransactionType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.ToTable("TransactionType", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "REWARD",
                            Name = "Reward"
                        },
                        new
                        {
                            Code = "SWAP",
                            Name = "Swap"
                        },
                        new
                        {
                            Code = "TRANSFER_IN",
                            Name = "Transfer In"
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Asset", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetType");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.TransactionType", "TransactionType")
                        .WithMany()
                        .HasForeignKey("TransactionTypeCode")
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_TransactionType");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
