// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Infrastructure.Persistence;

#nullable disable

namespace Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioContext))]
    [Migration("20260302211620_MigrateTransactionAssetsToGuids")]
    partial class MigrateTransactionAssetsToGuids
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AssetType");

                    b.HasKey("Id");

                    b.ToTable("Asset", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountReceived")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<decimal>("AmountSpent")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<Guid?>("FeeAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FeeAssetPriceInEur")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<decimal?>("FeeAssetPriceInUsd")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<Guid>("FromAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FromAssetPriceInEur")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<decimal>("FromAssetPriceInUsd")
                        .HasColumnType("decimal(36, 18)");

                    b.Property<string>("Notes")
                        .HasMaxLength(-1)
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ToAssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TransactionType");

                    b.Property<decimal?>("UsdEurExchangeRate")
                        .HasColumnType("decimal(18, 8)");

                    b.HasKey("Id")
                        .HasName("PK__YourTabl__3214EC0704F226F8");

                    b.HasIndex("FeeAssetId");

                    b.HasIndex("FromAssetId");

                    b.HasIndex("ToAssetId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Asset", "FeeAsset")
                        .WithMany()
                        .HasForeignKey("FeeAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Transaction_FeeAsset");

                    b.HasOne("Portfolio.Domain.Entities.Asset", "FromAsset")
                        .WithMany()
                        .HasForeignKey("FromAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_FromAsset");

                    b.HasOne("Portfolio.Domain.Entities.Asset", "ToAsset")
                        .WithMany()
                        .HasForeignKey("ToAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Transaction_ToAsset");

                    b.Navigation("FeeAsset");

                    b.Navigation("FromAsset");

                    b.Navigation("ToAsset");
                });
#pragma warning restore 612, 618
        }
    }
}
